name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Install the SDK
        2. Import `createProviderPlugin()`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / error output
      description: If applicable, add screenshots or paste error output to help explain the problem.

  - type: input
    id: sdk-version
    attributes:
      label: SDK version
      description: Version from your package.json dependency.
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows (WSL)
        - Windows (native)
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun version
      description: Output of `bun --version`.
      placeholder: "1.2.3"

  - type: dropdown
    id: plugin-type
    attributes:
      label: Plugin type
      description: Which plugin type is affected?
      options:
        - Provider
        - Agent
        - Theme
        - Notification
        - Helpers / utilities
        - Testing harness
        - Types (general)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error output, type errors, or build logs.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help — plugin code snippet, tsconfig, workarounds tried.
