name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for the plugin SDK? We'd love to hear it. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the pain point?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature or change you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the SDK does this affect?
      options:
        - Type definitions
        - Provider plugin interface
        - Agent plugin interface
        - Theme plugin interface
        - Notification plugin interface
        - Helper utilities
        - Auth / credential helpers
        - Testing harness
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big is this change?
      options:
        - Small (config, tweak, single type)
        - Medium (new helper, new interface, new test utility)
        - Large (architecture change, breaking type changes)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, code examples, links, or examples from other SDKs.
