// Types
export type {
  PluginId,
  PluginType,
  PluginPermissions,
  PluginMeta,
  ConfigField,
  BasePlugin,
  PluginLifecycleContext,
  PluginLogger,
  PluginHttpClient,
  AuthSources,
  OpenCodeAuthEntry,
  PluginStorage,
  PluginContext,
  CredentialSource,
  Credentials,
  OAuthCredentials,
  RefreshedCredentials,
  CredentialResult,
  ProviderAuth,
  ProviderCapabilities,
  ModelPricing,
  ProviderPricing,
  UsageLimit,
  CostBreakdown,
  ProviderUsageData,
  ProviderFetchContext,
  ProviderPlugin,
  AgentConfig,
  AgentCapabilities,
  AgentCredentials,
  AgentProviderConfig,
  SessionParseOptions,
  SessionUsageData,
  ActivityUpdate,
  ActivityCallback,
  AgentFetchContext,
  AgentPlugin,
  ColorScheme,
  ColorSchemePreference,
  ThemeColors,
  ThemeComponents,
  ThemePlugin,
  NotificationSeverity,
  NotificationEventType,
  NotificationEvent,
  NotificationContext,
  NotificationPlugin,
  AnyPlugin,
  PluginByType,
  PluginOfType,
} from './types/index.ts';

export { CURRENT_API_VERSION, PluginPermissionError } from './types/index.ts';

// Helpers
export {
  createProviderPlugin,
  createAgentPlugin,
  createThemePlugin,
  createNotificationPlugin,
  apiKeyCredential,
  oauthCredential,
  credentialFound,
  credentialMissing,
  credentialExpired,
  credentialInvalid,
  credentialError,
  isTokenExpired,
  SDK_VERSION,
  isCompatible,
  assertCompatible,
} from './helpers/index.ts';
